# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-15 23:49
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('ranking', models.PositiveIntegerField()),
                ('summary', models.TextField()),
                ('lastedited', models.DateTimeField()),
                ('clicktraffic', models.PositiveIntegerField()),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), size=None)),
            ],
        ),
    ]
