# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-22 23:37
from __future__ import unicode_literals

from django.db import migrations, models
import tagulous.models.fields
import tagulous.models.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scraper', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('ranking', models.IntegerField()),
                ('summary', models.TextField()),
                ('lastedited', models.DateTimeField()),
                ('dateadded', models.DateTimeField()),
                ('clicktraffic', models.PositiveIntegerField()),
                ('needs_summary', models.BooleanField(default=True)),
                ('num_tags', models.IntegerField(default=0)),
                ('articles', models.ManyToManyField(related_name='events', to='scraper.Article')),
            ],
        ),
        migrations.CreateModel(
            name='Tagulous_Event_tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField()),
                ('count', models.IntegerField(default=0, help_text='Internal counter of how many times this tag is in use')),
                ('protected', models.BooleanField(default=False, help_text='Will not be deleted when the count reaches 0')),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
            },
            bases=(tagulous.models.models.BaseTagModel, models.Model),
        ),
        migrations.AlterUniqueTogether(
            name='tagulous_event_tags',
            unique_together=set([('slug',)]),
        ),
        migrations.AddField(
            model_name='event',
            name='tags',
            field=tagulous.models.fields.TagField(_set_tag_meta=True, help_text='Enter a comma-separated tag string', to='summarize.Tagulous_Event_tags'),
        ),
    ]
