# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-17 21:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('summarize', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='_Tagulous_Event_tags',
            new_name='Tagulous_Event_tags',
        ),
    ]
