# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-04 02:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentViewer', '0002_auto_20170814_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='ranking',
            field=models.IntegerField(),
        ),
    ]
