# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-17 15:18
from __future__ import unicode_literals

from django.db import migrations, models
import tagulous.models.fields
import tagulous.models.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('summarize', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('authors', models.CharField(max_length=200)),
                ('content', models.CharField(max_length=90000)),
                ('url', models.CharField(max_length=300)),
                ('date', models.DateTimeField(verbose_name='date')),
                ('event_id', models.ManyToManyField(default=None, related_name='article', to='summarize.Event')),
            ],
        ),
        migrations.CreateModel(
            name='Tagulous_Article_tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField()),
                ('count', models.IntegerField(default=0, help_text='Internal counter of how many times this tag is in use')),
                ('protected', models.BooleanField(default=False, help_text='Will not be deleted when the count reaches 0')),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
            },
            bases=(tagulous.models.models.BaseTagModel, models.Model),
        ),
        migrations.AlterUniqueTogether(
            name='tagulous_article_tags',
            unique_together=set([('slug',)]),
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=tagulous.models.fields.TagField(_set_tag_meta=True, help_text='Enter a comma-separated tag string', to='scraper.Tagulous_Article_tags', on_delete=models.CASCADE),
        ),
    ]
