# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 23:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date'),
            preserve_default=False,
        ),
    ]
