# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-15 00:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='url',
            field=models.CharField(default='', max_length=800),
            preserve_default=False,
        ),
    ]
