# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-22 19:17
from __future__ import unicode_literals

from django.db import migrations, models
import tagulous.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scraper', '0001_initial'),
        ('summarize', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='event_id',
            field=models.ManyToManyField(default=None, related_name='article', to='summarize.Event'),
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=tagulous.models.fields.TagField(_set_tag_meta=True, help_text='Enter a comma-separated tag string', to='scraper.Tagulous_Article_tags'),
        ),
    ]
