# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-11-17 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.CharField(max_length=300),
        ),
    ]
