# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-22 20:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_auto_20171022_1917'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tagulous_Article_tags',
        ),
        migrations.RemoveField(
            model_name='article',
            name='tags',
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
