# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-09 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_article_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='authors',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.CharField(max_length=5000),
        ),
    ]
