# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-09 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0003_auto_20170909_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='authors',
            field=models.CharField(max_length=500),
        ),
    ]
