# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-22 20:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0003_auto_20171022_2018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='event_id',
        ),
    ]
